runtime: custom
env: flex

runtime_config:
  port: 8080

network:
  forwarded_ports:
    - 80/tcp

# service: client
# entrypoint: gunicorn -b :$PORT main:app
# runtime_config:
#   docker:
#     image: ${{ vars.ARTIFACT_REPO_REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.ARTIFACT_REPO_NAME }}/multi-client
#     mem_limit_gb: 0.128
#     env_variables:
#       REDIS_HOST: ${REDIS_HOST}
#       REDIS_PORT: ${REDIS_PORT}
#       PGUSER: ${PGUSER}
#       PGHOST: ${PGHOST}
#       PGDATABASE: ${PGDATABASE}
#       PGPASSWORD: ${PGPASSWORD}
#       PGPORT: ${PGPORT}

# service: server
# entrypoint: gunicorn -b :$PORT main:app
# runtime_config:
#   docker:
#     image: ${{ vars.ARTIFACT_REPO_REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.ARTIFACT_REPO_NAME }}/multi-server
#     mem_limit_gb: 0.128
#     env_variables:
#       REDIS_HOST: ${REDIS_HOST}
#       REDIS_PORT: ${REDIS_PORT}
#       PGUSER: ${PGUSER}
#       PGHOST: ${PGHOST}
#       PGDATABASE: ${PGDATABASE}
#       PGPASSWORD: ${PGPASSWORD}
#       PGPORT: ${PGPORT}

# service: worker
# entrypoint: gunicorn -b :$PORT main:app
# runtime_config:
#   docker:
#     image: ${{ vars.ARTIFACT_REPO_REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.ARTIFACT_REPO_NAME }}/multi-worker
#     mem_limit_gb: 0.128
#     env_variables:
#       REDIS_HOST: ${REDIS_HOST}
#       REDIS_PORT: ${REDIS_PORT}

# service: nginx
# entrypoint: nginx -g "daemon off;"
# runtime_config:
#   docker:
#     image: ${{ vars.ARTIFACT_REPO_REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.ARTIFACT_REPO_NAME }}/multi-nginx
#     mem_limit_gb: 0.128