name: Deploy Multi-Container Project
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:

    permissions:
      contents: 'read'
      id-token: 'write'

    env:
      ARTIFACT_REPO_NAME: docker-repo
      ARTIFACT_REPO_REGION: us-central1
      
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@v2
      
      - id: auth  
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_ID }}          
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          access_token_lifetime: 600s

      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.ARTIFACT_REPO_REGION }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build Docker image and test
        run: docker build -t ${{ env.ARTIFACT_REPO_REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ env.ARTIFACT_REPO_NAME }}/react-test -f ./client/Dockerfile.dev ./client
          
      - name: Run test suite
        run: docker run -e CI=true ${{ env.ARTIFACT_REPO_REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ env.ARTIFACT_REPO_NAME }}/react-test npm test

      - name: Finalization
        run: |
          docker build -t ${{ env.ARTIFACT_REPO_REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ env.ARTIFACT_REPO_NAME }}/multi-client ./client
          docker build -t ${{ env.ARTIFACT_REPO_REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ env.ARTIFACT_REPO_NAME }}/multi-nginx ./nginx
          docker build -t ${{ env.ARTIFACT_REPO_REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ env.ARTIFACT_REPO_NAME }}/multi-server ./server
          docker build -t ${{ env.ARTIFACT_REPO_REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ env.ARTIFACT_REPO_NAME }}/multi-worker ./worker
                
      - name: Push Docker image
        run: |
          docker push ${{ env.ARTIFACT_REPO_REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ env.ARTIFACT_REPO_NAME }}/multi-client
          docker push ${{ env.ARTIFACT_REPO_REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ env.ARTIFACT_REPO_NAME }}/multi-nginx
          docker push ${{ env.ARTIFACT_REPO_REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ env.ARTIFACT_REPO_NAME }}/multi-server
          docker push ${{ env.ARTIFACT_REPO_REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ env.ARTIFACT_REPO_NAME }}/multi-worker
      
      # - id: deploy
      #   name: Deploy Docker image
      #   uses: "google-github-actions/deploy-cloudrun@v0"
      #   with:
      #     image: ${{ env.IMAGE_NAME_DEPLOY }}
      #     region: asia-east1
      #     service: app
      #     flags: --port=80

      # # Example of using the output
      # - name: Test URL
      #   run: curl "${{ steps.deploy.outputs.url }}"