name: Deploy Multi-Container Project
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:

    permissions:
      contents: 'read'
      id-token: 'write'
      
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@v2
      
      - id: auth  
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER_LOCATION }}          
          service_account: ${{ vars.SERVICE_ACCOUNT }}
          access_token_lifetime: 600s

      - id: login
        name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ vars.ARTIFACT_REPO_REGION }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - id: build_dev
        name: Build Docker image and test
        run: docker build -t ${{ vars.ARTIFACT_REPO_REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.ARTIFACT_REPO_NAME }}/react-test -f ./client/Dockerfile.dev ./client

      - id: test
        name: Run test suite
        run: docker run -e CI=true ${{ vars.ARTIFACT_REPO_REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.ARTIFACT_REPO_NAME }}/react-test npm test

      - id: build_final
        name: Finalization
        run: |
          docker build -t ${{ vars.ARTIFACT_REPO_REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.ARTIFACT_REPO_NAME }}/multi-client ./client
          docker build -t ${{ vars.ARTIFACT_REPO_REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.ARTIFACT_REPO_NAME }}/multi-nginx ./nginx
          docker build -t ${{ vars.ARTIFACT_REPO_REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.ARTIFACT_REPO_NAME }}/multi-server ./server
          docker build -t ${{ vars.ARTIFACT_REPO_REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.ARTIFACT_REPO_NAME }}/multi-worker ./worker

      - id: push
        name: Push Docker image
        run: |
          docker push ${{ vars.ARTIFACT_REPO_REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.ARTIFACT_REPO_NAME }}/multi-client
          docker push ${{ vars.ARTIFACT_REPO_REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.ARTIFACT_REPO_NAME }}/multi-nginx
          docker push ${{ vars.ARTIFACT_REPO_REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.ARTIFACT_REPO_NAME }}/multi-server
          docker push ${{ vars.ARTIFACT_REPO_REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.ARTIFACT_REPO_NAME }}/multi-worker

  deploy:
    runs-on: ubuntu-latest    
    steps:
      - id: auth  
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER_LOCATION }}          
          service_account: ${{ vars.SERVICE_ACCOUNT }}
          access_token_lifetime: 600s

      - id: login
        name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ vars.ARTIFACT_REPO_REGION }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      
      - id: setup_sdk
        name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: '${{ vars.PROJECT_ID }}'

      - id: deploy_postgres
        name: Deploy Postgres Latest
        uses: "google-github-actions/deploy-cloudrun@v0"
        with:
          image: "postgres:latest"
          env_vars: |
            POSTGRES_PASSWORD=postgres_password
          service: 'postgres'

      - id: deploy_redis
        name: Deploy Redis Latest
        uses: "google-github-actions/deploy-cloudrun@v0"
        with:
          image: "redis:latest"
          service: 'redis'

      # # Example of using the output
      # - name: Test URL
      #   run: curl "${{ steps.deploy.outputs.url }}"